name: Test Teraslice Asset
run-name: ${{ github.actor }} is testing the Teraslice Asset
on:
  workflow_call:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # NOTE: Hard Coded Node Version array, should match array in build-and-publish-asset.yml
        node-version: [18.19.1, 20.11.1, 22.2.0]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # we login to docker to avoid docker pull limit rates
      # secrets are now duplicated for Actions and Dependabot
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: yarn setup
      - run: yarn lint
      - run: yarn test:all
      - run: yarn global add teraslice-cli
      - run: teraslice-cli -v
      - run: teraslice-cli assets build
      - run: ls -l build/

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # NOTE: Hard Coded Node Version
          node-version: '18.19.1'
      # NOTE: Prevent python 3.12 breaking node-gyp installations in the kafka asset
      # TODO: try default python again in the future 
      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: yarn setup
      - run: yarn lint
      # TODO: Ideally we'd be able to at least run unit tests that don't require docker.
      #- run: yarn test:all
      - run: yarn global add teraslice-cli
      - run: teraslice-cli -v
      - run: teraslice-cli assets build
      - run: ls -l build/
