name: Cache Asset Bundles If No Cache Found

on:
  workflow_call:

jobs:
  cache-asset-bundles:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install and build packages
      run: yarn && yarn setup

    - name: Build e2e directory
      run: yarn build
      working-directory: ./e2e

    - name: Generate asset bundle list
      run: yarn download-assets generate-list
      working-directory: ./e2e

    - name: Check for asset bundle cache
      id: asset-bundles-cache
      uses: actions/cache@v4
      with:
        path: /tmp/teraslice_assets
        key: asset-bundles-${{ hashFiles('./e2e/scripts/ci_asset_bundle_list.txt') }}
        lookup-only: true

    - name: Pull and save asset bundles if no cache hit
      if: ${{steps.asset-bundles-cache.outputs.cache-hit != 'true'}}
      run: yarn download-assets download

    - name: Update asset bundles cache if no cache hit
      if: ${{steps.asset-bundles-cache.outputs.cache-hit != 'true'}}
      uses: actions/cache/save@v4
      with:
        path: /tmp/teraslice_assets
        key: asset-bundles-${{ hashFiles('./e2e/scripts/ci_asset_bundle_list.txt') }}