name: Cache Docker Images If No Cache Found

on:
  workflow_call:

jobs:
  cache-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    # we login to docker to avoid docker pull limit rates
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install and build packages
      run: yarn setup
      env:
        YARN_SETUP_ARGS: "--prod=false --silent"

    - name: Create Docker Image List
      id: image-list
      run: |
        yarn docker:listImages
        echo "LIST_CONTENTS=$( cat ./images/image-list.txt )" >> $GITHUB_OUTPUT 

    - name: Check for Docker image cache
      id: docker-cache
      uses: actions/cache@v4
      with:
        path: /tmp/docker_cache
        key: docker-images-${{ hashFiles('./images/image-list.txt') }}
        lookup-only: true

    - name: Pull and save Docker images if no cache hit
      if: ${{steps.docker-cache.outputs.cache-hit != 'true'}}
      run: yarn docker:saveImages

    - name: Update Docker image cache if no cache hit
      if: ${{steps.docker-cache.outputs.cache-hit != 'true'}} && ${{steps.image-list.outputs.LIST_CONTENTS != ''}}
      uses: actions/cache/save@v4
      with:
        path: /tmp/docker_cache
        key: docker-images-${{ hashFiles('./images/image-list.txt') }}