name: Check Github API Rate limit

on:
  workflow_call:

permissions: {}

jobs:
  check-github-api-rate-limit:
    runs-on: ubuntu-latest
    steps:
    - name: Check Github API rate limit Unauthorized
      run: curl -Ss https://api.github.com/rate_limit
    - name: Check Github API rate limit Authorized
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh api /rate_limit
