name: Check Docker Pull Rate Limit

on:
  workflow_call:

jobs:
  check-docker-limit-before:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check docker.hub limit start
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: yarn docker:limit