name: Check Docker Pull Rate Limit

on:
  workflow_call:

jobs:
  check-docker-pull-rate-limit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Yarn 4
      run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        yarn install

    - name: Check docker.hub pull limit
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: yarn docker:limit