name: Check Docker Pull Rate Limit

on:
  workflow_call:

jobs:
  check-docker-pull-rate-limit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check docker.hub pull limit
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: yarn && yarn docker:limit
