name: Refresh Docker Cache

on:
  workflow_call:

jobs:
  Check-docker-limit-before:
    uses: ./.github/workflows/check-docker-limit.yml
    secrets: inherit

  refresh-docker-cache:
    runs-on: ubuntu-latest
    needs: Check-docker-limit-before

    # # final check to make sure it runs only on master branch
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    # we login to docker to avoid docker pull limit rates
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install and build packages
      run: yarn && yarn setup

    - name: Create Docker Image List
      run: |
        yarn docker:listImages
        cat ./images/image-list.txt

    - name: Check for Docker image cache
      id: docker-cache
      uses: actions/cache@v4
      with:
        path: /tmp/docker_cache
        key: docker-images-${{ hashFiles('./images/image-list.txt') }}
        lookup-only: true

    - name: Clear old docker cache if present
      if: ${{steps.docker-cache.outputs.cache-hit == 'true'}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        BRANCH: refs/heads/master
      run: |
        gh extension install actions/gh-actions-cache

        echo "Fetching list of cache key"
        cacheKeysForPR=$(gh actions-cache list --key "docker-images-" -R $REPO -B $BRANCH -L 100 | cut -f 1 )

        ## Setting this to not fail the workflow while deleting cache keys.
        set +e
        echo "Deleting caches..."
        for cacheKey in $cacheKeysForPR
        do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
        done
        echo "Done"

    - name: Pull and save Docker images
      run: yarn docker:saveImages

    - name: Update Docker image cache
      uses: actions/cache/save@v4
      with:
        path: /tmp/docker_cache
        key: docker-images-${{ hashFiles('./images/image-list.txt') }}

  Check-docker-limit-after:
    needs: refresh-docker-cache
    uses: ./.github/workflows/check-docker-limit.yml
    secrets: inherit
